---
abstract: 'easy subclassing of non-Moose classes'
author:
  - 'Jesse Luehrs <doy@tozt.net>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.88
  base: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-NonMoose
provides:
  MooseX::NonMoose:
    file: lib/MooseX/NonMoose.pm
    version: 0.23
  MooseX::NonMoose::InsideOut:
    file: lib/MooseX/NonMoose/InsideOut.pm
    version: 0.23
  MooseX::NonMoose::Meta::Role::Class:
    file: lib/MooseX/NonMoose/Meta/Role/Class.pm
    version: 0.23
  MooseX::NonMoose::Meta::Role::Constructor:
    file: lib/MooseX/NonMoose/Meta/Role/Constructor.pm
    version: 0.23
requires:
  List::MoreUtils: 0
  Module::Runtime: 0
  Moose::Exporter: 0
  Moose::Role: 2.0000
  warnings: 0
resources:
  bugtracker: https://github.com/doy/moosex-nonmoose/issues
  homepage: http://metacpan.org/release/MooseX-NonMoose
  repository: git://github.com/doy/moosex-nonmoose.git
version: 0.23
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@DOY/TestMoreDoneTesting'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@DOY/GatherDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DOY/PruneCruft'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DOY/ManifestSkip'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DOY/MetaYAML'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::License
      name: '@DOY/License'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@DOY/Readme'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@DOY/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DOY/ExecDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DOY/ShareDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@DOY/MakeMaker'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DOY/Manifest'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DOY/TestRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DOY/ConfirmRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DOY/MetaConfig'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DOY/MetaJSON'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DOY/NextRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@DOY/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DOY/PkgVersion'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@DOY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@DOY/PodCoverageTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DOY/PodSyntaxTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@DOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@DOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@DOY/Test::Compile'
      version: 2.002
    -
      class: Dist::Zilla::Plugin::Metadata
      name: '@DOY/Metadata'
      version: 3.03
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@DOY/MetaResources'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@DOY/Git::Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@DOY/Git::Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@DOY/Git::Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@DOY/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@DOY/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@DOY/MetaProvides::Package'
      version: 1.14000002
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@DOY/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DOY/UploadToCPAN'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300035
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300035
x_authority: cpan:DOY
x_contributors:
  - 'Brian Phillips <brian@thephillips.info>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
  - 'Jason May <jason.a.may@gmail.com>'
