---
abstract: 'foreign inheritance for Moose'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-NonMoose
requires:
  Moose: 0.83
version: 0.05
