--- 
abstract: foreign inheritance for Moose
author: 
  - Jesse Luehrs <doy at tozt dot net>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: MooseX-NonMoose
requires: 
  Moose: 0.76
version: 0.03
